### ISSUE TITLE
Specify behavior for unleakable functions

### ISSUE THREAD

**Issue by jorendorff** [claudepache/es-legacy-function-reflection#2]
Even the current "complete" Version 1 specification leaves this unspecified. It would be better to have this specified one way or the other, for web compatibility.

**Comment by claudepache** [comment]
Since this Issue has been opened, the spec has been updated, so that now there is no unspecified part left.

However I’m leaving this Issue open at least until the outcome of the next TC39 meeting. Indeed, in tc39/ecma262#562, @rossberg raised objections to a precise specification.

**Comment by claudepache** [comment]
> However I’m leaving this Issue open at least until the outcome of the next TC39 meeting. Indeed, in [tc39/ecma262#562](https://github.com/tc39/ecma262/issues/562), @rossberg raised objections to a precise specification.

I’ve changed my mind: allowing undeterministic behaviour would be a precedent; therefore if someone wants to have the liberty to apply incorrect optimisations to sloppy functions, they should request it explicitly.

Therefore, I’m closing this issue as fixed. Another issue may be opened by anyone that has a good reason to wanting to leave parts unspecified.
