### ISSUE TITLE
Strict functions and non-ECMAScript functions should be undistinguishable

### ISSUE THREAD

**Issue by claudepache** [claudepache/es-legacy-function-reflection#6]
Consider:

```js
[1,2].reduce(function () {
    return this.caller
})
```

As currently specified, depending on whether an implementation chooses to implement `Array.prototype.reduce` as an ECMAScript function or not, that will throw an error or return null. (Recall that builtin functions that are implemented in ECMAScript are required to be strict for good reason.)

Therefore, we will switch to the V8 semantics, for which null is returned in both cases.

**Comment by Jack-Works** [comment]
IIRC, the bound function is non ecmascript function.

Consider the following code:

```js
function x() {
    a = 1 // should be error in strict mode
}
y = x.bind(null, 1)
y.toString() // native code
```

Should y behave like strict function or not?

**Comment by claudepache** [comment]
> IIRC, the bound function is non ecmascript function.

@Jack-Works Indeed, and therefore a bound function has the same behaviour as a strict function in situations where strict functions and non-ECMAScript functions are not distinguishable. This is what current implementations do: try to enter `(function(){}).caller`, then 
`(function(){}).bind().caller` in the console of your favourite browser.

But beware of another subtlety: A bound functions is never considered as the “caller” of another function, because the determination of the “caller” is based on the execution context stack.
